### PR TITLE
fix(bridge): fix message not forwarded due to double-encoded config

### LINKED ISSUE #197: 桥接转发插件不可用
刚刚测试了，无法推送消息到回调地址

### PR DESCRIPTION
**Pull request by whhjdi**
## Problem / Intent

Fixes #197. The Bridge plugin failed to forward messages to the callback URL after installation.

Root cause: the frontend double-serialized the installation config — `JSON.stringify` was called explicitly in the `config` field, and then `api.ts` serialized the entire request body again. This caused the DB to store the config as a JSON-encoded string (e.g. `"{\"forward_url\":\"...\"}"`) instead of a JSON object. The bridge handler's `json.Unmarshal` then failed silently and returned early, skipping the forward entirely.

## Approach

- **Frontend fix**: remove the redundant `JSON.stringify` in `install-app.tsx` and `installation-detail.tsx` — pass the raw config object directly
- **Backend API defense**: `handleUpdateInstallation` now detects and unwraps double-encoded config on new saves, fixing data going forward
- **Bridge handler defense**: handler now attempts to unwrap double-encoded config on read, recovering existing bad data without requiring users to re-save
- **Regression test**: `TestHandler_DoubleEncodedConfig` reproduces the bug (forwarded=false) and verifies the fix (forwarded=true)

## Summary by CodeRabbit

* **Bug Fixes**
  * Fix: double-encoded JSON configs are now detected and unwrapped so stored configs and event forwarding work reliably; parsing errors no longer cause silent skips.
  * Install flows now persist config as structured data and surface a “配置保存失败” toast on save failure.

* **Tests**
  * Added tests covering object configs, double-encoded object strings, and non-object string configs.

### CODE REVIEW

**Review by Bowl42 — COMMENTED** [review]
## Code Review

**整体评价：** 修复正确，三层防御策略（前端根因 + 后端写入防御 + 后端读取防御）合理。

### 需要修复

1. **变量名 `s` 遮蔽了方法接收者 `(s *Server)`** — `app_install_handler.go` 里 `var s string` 和方法接收者重名，建议改为 `raw` 或 `str`，同时可以简化逻辑：
   ```go
   cfg = req.Config
   var raw string
   if json.Unmarshal(req.Config, &raw) == nil {
       if unwrapped := json.RawMessage(raw); json.Valid(unwrapped) {
           cfg = unwrapped
       }
   }
   ```

2. **建议给 `handler.go` 里的运行时 unwrap 加 TODO 注释** — 这段代码会在每次事件处理时执行，应标记 `// TODO: remove after data migration`，后续做一次性数据修复清理掉

### 建议（非阻塞）

- 测试注释说"复现 skip"，但实际测试的是修复后能正常转发，描述可以更准确
- 两个 `.tsx` 文件大量 prettier 格式化变更混在 bugfix 里，增加 review 难度，建议以后分开提交
- 可以考虑把 double-encode unwrap 逻辑抽成共享 helper，减少重复
- 缺少 `handleUpdateInstallation` 写入端的单元测试覆盖

**Review by Bowl42 — COMMENTED** [review]
## Codex 补充 Review

1. **unwrap 逻辑过于宽泛** — 当前实现会把任何合法 JSON 字符串（如 `"123"`、`"null"`、`"[]"`）都 unwrap，不只是 object。更安全的做法是只在解码后的值是 JSON object（`{` 开头）时才 unwrap，避免意外改变合法 payload 的语义：
   ```go
   cfg = req.Config
   var raw string
   if json.Unmarshal(req.Config, &raw) == nil {
       if unwrapped := json.RawMessage(raw); json.Valid(unwrapped) && len(unwrapped) > 0 && unwrapped[0] == '{' {
           cfg = unwrapped
       }
   }
   ```

2. **缺少 API 层测试** — 只测了 bridge handler 的读取端 unwrap，没有测 `handleUpdateInstallation` 写入端。建议加一个 API 测试验证 `config: {...}` 和 `config: "{\"forward_url\":...}"` 最终存储结果一致

**Review by Bowl42 — APPROVED** [review]
## Code Review: fix(bridge) -- double-encoded config

**Verdict: APPROVE**

This is a well-structured fix that addresses the root cause (frontend double-serialization) while also adding backend defense-in-depth for both the write path and the read path. All tests pass.

### What was done well

- **Root cause + defense-in-depth**: The PR correctly removes the redundant `JSON.stringify` at both frontend call sites (`install-app.tsx` and `installation-detail.tsx`), AND adds backend unwrap guards to handle legacy data and any future regressions. This layered approach is the right call.
- **Guard narrowness**: The `unwrapped[0] == '{'` check prevents the unwrap from silently rewriting non-object JSON strings (arrays, numbers, null), which is important to avoid data corruption.
- **Test coverage**: Three meaningful test cases in the API test (normal, double-encoded, non-object string) and a regression test in the bridge handler that reproduces the original bug scenario.
- **TODO annotation**: The bridge handler unwrap is correctly marked for removal after a data migration, keeping the tech debt visible.

### Minor observations (no changes required)

1. **Bridge handler test comment vs. behavior**: `TestHandler_DoubleEncodedConfig` comments say it "reproduces" the bug (forwarded=false), but in practice the test now verifies the fix works (forwarded=true). The comment and test name could be slightly misleading to a future reader, but this is cosmetic.

2. **Silent discard of inner Unmarshal error** (bridge `handler.go` line 36): The inner `json.Unmarshal([]byte(raw), &cfg)` error is discarded. This is acceptable since the subsequent `cfg.ForwardURL == ""` check catches the failure, and the code is slated for removal anyway.

3. **Frontend formatting changes**: The diff includes extensive Prettier-style reformatting in both `.tsx` files (import grouping, line breaks, JSX formatting). These are harmless but inflate the diff size. Consider running the formatter separately in a dedicated commit to keep bug-fix diffs focused. Not a blocker.

### Completeness check

- Verified that `install-app.tsx` line 114 and `installation-detail.tsx` line 680 were the ONLY two call sites passing `JSON.stringify(configForm)` to `updateInstallation`. All other `updateInstallation` callers (`handle`, `enabled` updates in `installation-detail.tsx` and `bot-apps-tab.tsx`) do not touch config. The frontend fix is complete.
- Bridge is the only builtin handler that reads `inst.Config`, so no other handlers need the same unwrap treatment.
- `api.ts` confirms `updateInstallation` already wraps the full body in `JSON.stringify(data)`, validating the double-encoding root cause.

File: web/src/pages/install-app.tsx [hunk 1]
```diff
@@ -86,7 +95,11 @@ export function InstallAppPage() {
...
         setWaitingForOAuth(true);
-        const popup = window.open(result.oauth_redirect, "oauth_popup", "width=600,height=700,scrollbars=yes");
+        const popup = window.open(
+          result.oauth_redirect,
+          "oauth_popup",
+          "width=600,height=700,scrollbars=yes",
+        );
         setOAuthPopup(popup);
         setInstalling(false);
         return;
```
Comment (Bowl42) [inline web/src/pages/install-app.tsx:137]: If an app requires OAuth, we return here before the new `updateInstallation(..., { config: configForm })` call. The completion handler at the top of this component only closes the popup and navigates back to the bot page, so any config entered on this screen is dropped for `needs_oauth` installs. That means the frontend fix is still incomplete for apps that need both OAuth and `config_schema`.

**Review by Bowl42 — COMMENTED** [review]
1 finding.

- The backend unwrap logic looks correct for the reported double-encoded-object case, and the object-only guard avoids rewriting quoted `[]`, `123`, or `null` payloads. The remaining gap is on the frontend OAuth install path: if `installApp()` returns `needs_oauth`, this page returns before the `updateInstallation(..., { config })` call and the completion handler only navigates away, so config entered on the install page is never persisted for apps that require both OAuth and `config_schema`.

Test coverage is good for the main regression (`TestHandleUpdateInstallation_ConfigUnwrap`, `TestHandler_DoubleEncodedConfig`), but I did not see automated coverage for raw `null` / array / number configs or for the OAuth install flow above.

**Comment by Bowl42** [comment]
@coderabbitai review

**Review by Bowl42 — APPROVED** [review]
All previous review findings have been addressed. Verified:

**Previous finding: OAuth + config_schema gap** — RESOLVED
- `saveConfigIfNeeded` helper extracted and called from both OAuth completion paths (message handler and polling fallback)
- `oauthInstallationId` state correctly tracks the installation ID across the OAuth flow
- Installation ID captured from `installApp()` response before entering the OAuth waiting state

**Core fix remains sound:**
- Frontend: redundant `JSON.stringify` removed from both `install-app.tsx` and `installation-detail.tsx` (`config: form` instead of `config: JSON.stringify(form)`)
- Backend write-path: `handleUpdateInstallation` unwraps double-encoded config with object-only guard (`unwrapped[0] == '{'`)
- Backend read-path: bridge handler unwraps on read for existing bad data, with TODO for removal after migration

**Tests:** All passing — `TestHandleUpdateInstallation_ConfigUnwrap` (3 sub-tests: normal, double-encoded, non-object guard) and `TestHandler_DoubleEncodedConfig` (regression test).

**Formatting:** The diff includes Prettier reformatting of both `.tsx` files. These are style-only changes (line wrapping, JSX attribute formatting) and do not affect behavior.

No new issues found. LGTM.

**Review by Bowl42 — COMMENTED** [review]
The OAuth + config fix is still incomplete. In `web/src/pages/install-app.tsx`, the popup `oauth_complete` handler now calls `saveConfigIfNeeded(oauthInstallationId)`, but `oauthInstallationId` is never populated for the OAuth setup flow. `POST /api/apps/{id}/install` still returns only `needs_oauth` + `oauth_redirect` in `internal/api/app_install_handler.go:438-446`, and `/oauth/complete` still posts only `{type:"oauth_complete"}` in `internal/api/app_oauth_handler.go:223-227`. That means the common popup-success path still navigates away without saving config; only the polling fallback can save it if it wins the race. This still needs an installation ID passed through one of those paths before the frontend-side fix is correct.

**Comment by Bowl42** [comment]
Re: Codex multi-install concern — this is a pre-existing limitation of the OAuth flow design, not introduced by this PR. In practice:
- `listBotApps` returns `ORDER BY created_at DESC` (newest first), so `find` matches the just-created installation
- The multi-install + OAuth + config_schema combination is extremely rare
- The proper fix would require the OAuth callback to include the installation ID, which is a larger refactor

This PR's scope is fixing double-encoded config. The OAuth config save is a bonus improvement over the previous behavior (which was: never save config after OAuth at all).

@coderabbitai review

**Review by Bowl42 — APPROVED** [review]
LGTM. The multi-install edge case is a pre-existing OAuth flow limitation, not introduced by this PR. The double-encoded config fix and OAuth config save improvement are both correct.
